- hosts: localhost
  connection: local
 
  tasks:
   - name: Start the instances
     ec2:
       aws_access_key: "{{aws_access_key}}"
       aws_secret_key: "{{aws_secret_key}}"
       instance_ids: "{{ item }}"
       region: "{{ region }}"
       state: running
       wait: True
     with_items: "{{ instance_ids }}"
     register: start_instance
     tags: start
   - pause:
       minutes: 2

    - action:
        module: ec2_elb_facts
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        region: "{{region}}"
        names: "{{elb_name}}"
      register: elb_old_state
      tags: elb
    - name: Register instances {{instance_ids}}
      local_action: ec2_elb
      args:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        ec2_elbs: "{{elb_name}}"
        region: "{{region}}"
        instance_id: "{{item}}"
        validate_certs: no
        enable_availability_zone: yes
        wait: yes
        state: present
      with_items: "{{instance_ids}}"
      tags: register
